name: Install and cache
description: Setup JS workflow, install dependencies and cache them
author: chillios-ts

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.0

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
