export const TELEGRAM_URL = 'https://t.me/thorswap_ann'
export const DISCORD_URL = 'https://discord.com/invite/thorswap'
export const TWITTER_URL = 'https://twitter.com/THORSwap'
export const MEDIUM_URL = 'https://thorswap.medium.com'
export const BUILD_NUMBER = 'DEVELOPMENT_BUILD'
export const V1_URL = 'https://app.thorswap.finance/'
export const THORSWAP_YOUTUBE_URL = 'https://www.youtube.com/thorswapcommunity'
export const THORSWAP_FEEDBACK_URL = 'https://thorswap.canny.io/'
export const THORSWAP_DOCUMENTATION_URL =
  'https://docs.thorswap.finance/thorswap/'
export const THORCHADS_MERCH_URL = 'https://thorchads.metaswagclub.com/'
