export const TELEGRAM_URL = 'https://t.me/thorswap_ann'
export const DISCORD_URL = 'https://discord.com/invite/thorswap'
export const TWITTER_URL = 'https://twitter.com/THORSwap'
export const MEDIUM_URL = 'https://thorswap.medium.com'
export const BUILD_NUMBER = 'DEVELOPMENT_BUILD'
export const V1_URL = 'https://app.thorswap.finance/'
