name: Development Build & deploy

on:
  push:
    branches:
      - develop

concurrency:
  group: dev-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save build date
        run: echo "BUILD_DATE=$(date +"%Y-%m-%d")" > $GITHUB_ENV

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      # See: https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ steps.nvm.outputs.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Save action build number
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'DEVELOPMENT_BUILD'
          replace: ${{ env.BUILD_DATE }}
          include: 'src/config/constants.ts'

      # `--prefer-offline` gives cache priority
      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build project
        env:
          VITE_ALCHEMY_KEY: ${{ secrets.VITE_ALCHEMY_KEY }}
          VITE_ALLTHATNODE_KEY: ${{ secrets.VITE_ALLTHATNODE_KEY }}
          VITE_BLOCKCHAIR_API_KEY: ${{ secrets.VITE_BLOCKCHAIR_API_KEY }}
          VITE_COVALENT_API_KEY: ${{ secrets.VITE_COVALENT_API_KEY }}
          VITE_DOGENODE_API_KEY: ${{ secrets.VITE_DOGENODE_API_KEY }}
          VITE_ETHERSCAN_API_KEY: ${{ secrets.VITE_ETHERSCAN_API_KEY }}
          VITE_ETHPLORER_API_KEY: ${{ secrets.VITE_ETHPLORER_API_KEY }}
          VITE_FIGMENT_API_KEY: ${{ secrets.VITE_FIGMENT_API_KEY }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
          VITE_KADO_KEY: ${{ secrets.VITE_KADO_KEY }}
          VITE_MAINNET_THORNODE: ${{ secrets.VITE_MAINNET_THORNODE }}
          VITE_THORSWAP_API: ${{ secrets.VITE_THORSWAP_API }}
          VITE_THORSWAP_DEV_API: ${{ secrets.VITE_THORSWAP_DEV_API }}

        run: yarn build

      - name: Cypress E2E Tests
        uses: cypress-io/github-action@v4
        with:
          start: yarn preview --host
          browser: chrome

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: ./dist

      - name: Upload test videos
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: ./cypress/videos

  deploy-beta:
    name: Deploy beta to Netlify
    needs: build
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-beta]') }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: ./dist

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: develop
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
        timeout-minutes: 1

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Deployed ✅ - https://beta.thorswap.finance\nEnvironment: mainnet\nAuthor: ${{ github.actor }}"

  deploy-dev:
    name: Deploy dev to Netlify
    needs: build
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-dev]') }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: ./dist

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: develop
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_API_SITE_ID }}
        timeout-minutes: 1

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Deployed ✅ - https://dev.thorswap.finance\nEnvironment: mainnet\nAPI: dev-api\nAuthor: ${{ github.actor }}"
