name: Development Build & deploy

on:
  push:
    branches:
      - develop

concurrency:
  group: dev-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save build date
        run: echo "BUILD_DATE=$(date +"%Y-%m-%d")" > $GITHUB_ENV

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      # See: https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ steps.nvm.outputs.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Save action build number
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'DEVELOPMENT_BUILD'
          replace: ${{ env.BUILD_DATE }}
          include: 'src/config/constants.ts'

      # `--prefer-offline` gives cache priority
      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build project
        env:
          CI: false
          VITE_NETWORK: ${{ secrets.VITE_NETWORK }}
          VITE_MAINNET_THORCHAIN_RPC: ${{ secrets.VITE_MAINNET_THORCHAIN_RPC }}
          VITE_MAINNET_THORNODE: ${{ secrets.VITE_MAINNET_THORNODE }}
          VITE_IS_SYNTH_ACTIVE: true
          VITE_DOGENODE_API_KEY: ${{ secrets.VITE_DOGENODE_API_KEY }}
          VITE_ETHERSCAN_API_KEY: ${{ secrets.VITE_ETHERSCAN_API_KEY }}
          VITE_ETHPLORER_API_KEY: ${{ secrets.VITE_ETHPLORER_API_KEY }}
          VITE_INFURA_PROJECT_ID: ${{ secrets.VITE_INFURA_PROJECT_ID }}
          VITE_IS_NETWORK_ONLINE: ${{ secrets.VITE_IS_NETWORK_ONLINE }}
          VITE_FIGMENT_API_KEY: ${{ secrets.VITE_FIGMENT_API_KEY }}
          VITE_AFFILIATE_ON: false

        run: yarn build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy to Netlify
    needs: build
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/develop'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-branch: develop
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
        timeout-minutes: 1

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'THORSwap V2 development app has been deployed. - https://beta.thorswap.finance'
