name: Vercel Ledger Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_LEDGER_PROJECT_ID }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

concurrency:
  group: ledger-prodcution-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
      - name: Decrypt Secrets
        shell: bash
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output ./.env ./.env.gpg

      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@49249df836477f28dda1ee275d3c04c136b722a3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          teamId: ${{ secrets.VERCEL_ORG_ID }}
          projectName: ledger-live
          envVariableKeys: VITE_BLOCKCHAIR_API_KEY,VITE_COVALENT_API_KEY,VITE_ETHPLORER_API_KEY,VITE_POSTHOG_API_KEY,VITE_WALLETCONNECT_PROJECT_ID
        env:
          VITE_BLOCKCHAIR_API_KEY: ${{ secrets.VITE_BLOCKCHAIR_API_KEY }}
          TARGET_VITE_BLOCKCHAIR_API_KEY: production,preview,development
          TYPE_VITE_BLOCKCHAIR_API_KEY: encrypted
          VITE_COVALENT_API_KEY: ${{ secrets.VITE_COVALENT_API_KEY }}
          TARGET_VITE_COVALENT_API_KEY: production,preview,development
          TYPE_VITE_COVALENT_API_KEY: encrypted
          VITE_ETHPLORER_API_KEY: ${{ secrets.VITE_ETHPLORER_API_KEY }}
          TARGET_VITE_ETHPLORER_API_KEY: production,preview,development]
          TYPE_VITE_ETHPLORER_API_KEY: encrypted
          VITE_WALLETCONNECT_PROJECT_ID: ${{ secrets.VITE_WALLETCONNECT_PROJECT_ID }}
          TARGET_VITE_WALLETCONNECT_PROJECT_ID: production,preview,development
          TYPE_VITE_WALLETCONNECT_PROJECT_ID: encrypted
          VITE_POSTHOG_API_KEY: ${{ secrets.VITE_POSTHOG_API_KEY }}
          TARGET_VITE_POSTHOG_API_KEY: production,preview,development
          TYPE_VITE_POSTHOG_API_KEY: encrypted
          VITE_STAGING_API_KEY: ${{ secrets.VITE_STAGING_API_KEY }}
          TARGET_VITE_STAGING_API_KEY: production,preview,development
          TYPE_VITE_STAGING_API_KEY: encrypted
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          TARGET_VITE_API_KEY: production
          TYPE_VITE_API_KEY: encrypted

      - name: Deploy to Vercel
        id: vercel
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} | tee vercel-deploy.log
          echo "vercel_url=$(cat vercel-deploy.log)" >> "$GITHUB_OUTPUT"

      - name: Discord Notification
        uses: sarisia/actions-status-discord@82409b24a08684f54ea5baa6b376e36dad37fb81
        with:
          noprefix: ${{ job.status == 'success' }}
          avatar_url: https://static.thorswap.finance/logo.png
          color: 0x238636
          description: 'Ledger Prod Deployment'
          status: success
          url: 'https://ledgerlive.thorswap.finance'
          username: Ledger Production Deployment
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
