name: Lint & Unit tests

on:
  push:
    branches-ignore:
      - 'stagenet'
      - 'testnet'
      - 'main'

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint
          yarn typescript

      # - name: Tests
      #   run: yarn test:ci
