name: Lint & Unit tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo

      - name: Lint
        run: |
          bun lint
          bun typescript

      # - name: Tests
      #   run: bun test:ci
