name: Lint & Unit tests

on: [workflow_dispatch, pull_request]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo

      - name: Lint
        run: |
          yarn lint
          yarn typescript

      # - name: Tests
      #   run: yarn test:ci
