name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          teamId: ${{ secrets.VERCEL_ORG_ID }}
          projectName: dex-web
          envVariableKeys: VITE_BLOCKCHAIR_API_KEY,VITE_COVALENT_API_KEY,VITE_ETHPLORER_API_KEY,VITE_WALLETCONNECT_PROJECT_ID
        env:
          VITE_BLOCKCHAIR_API_KEY: ${{ secrets.VITE_BLOCKCHAIR_API_KEY }}
          TARGET_VITE_BLOCKCHAIR_API_KEY: production,preview,development
          TYPE_VITE_BLOCKCHAIR_API_KEY: encrypted
          VITE_COVALENT_API_KEY: ${{ secrets.VITE_COVALENT_API_KEY }}
          TARGET_VITE_COVALENT_API_KEY: production,preview,development
          TYPE_VITE_COVALENT_API_KEY: encrypted
          VITE_ETHPLORER_API_KEY: ${{ secrets.VITE_ETHPLORER_API_KEY }}
          TARGET_VITE_ETHPLORER_API_KEY: production,preview,development
          TYPE_VITE_ETHPLORER_API_KEY: encrypted
          VITE_WALLETCONNECT_PROJECT_ID: ${{ secrets.VITE_WALLETCONNECT_PROJECT_ID }}
          TARGET_VITE_WALLETCONNECT_PROJECT_ID: production,preview,development
          TYPE_VITE_WALLETCONNECT_PROJECT_ID: encrypted

          # Feature envs
          # GIT_VITE_ETHPLORER_API_KEY: feature/foo

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Discord Preview Notification
      #   env:
      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #   uses: Ilshidur/action-discord@master
      #   with:
      #     args: "Deployed ✅ - https://app.thorswap.finance\nEnvironment: mainnet\nAuthor: ${{ github.actor }}"
