name: Sdk test Build & deploy

on:
  push:
    branches:
      - feat/migrate-thorswap-sdk

concurrency:
  group: sdk-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo

      - name: Build project
        env:
          VITE_ALCHEMY_KEY: ${{ secrets.VITE_ALCHEMY_KEY }}
          VITE_ALLTHATNODE_KEY: ${{ secrets.VITE_ALLTHATNODE_KEY }}
          VITE_BLOCKCHAIR_API_KEY: ${{ secrets.VITE_BLOCKCHAIR_API_KEY }}
          VITE_COVALENT_API_KEY: ${{ secrets.VITE_COVALENT_API_KEY }}
          VITE_DOGENODE_API_KEY: ${{ secrets.VITE_DOGENODE_API_KEY }}
          VITE_ETHERSCAN_API_KEY: ${{ secrets.VITE_ETHERSCAN_API_KEY }}
          VITE_ETHPLORER_API_KEY: ${{ secrets.VITE_ETHPLORER_API_KEY }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
          VITE_KADO_KEY: ${{ secrets.VITE_KADO_KEY }}
          VITE_WALLETCONNECT_PROJECT_ID: ${{ secrets.VITE_WALLETCONNECT_PROJECT_ID }}
          VITE_MAINNET_THORNODE: ${{ secrets.VITE_MAINNET_THORNODE }}
          VITE_THORSWAP_API: ${{ secrets.VITE_THORSWAP_API }}
          VITE_THORSWAP_DEV_API: ${{ secrets.VITE_THORSWAP_DEV_API }}

        run: yarn build

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: ./dist

  deploy:
    name: Deploy beta to Netlify
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: ./dist

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: feat/migrate-thorswap-sdk
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SDK_TEST_SITE_ID }}
        timeout-minutes: 1

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Deployed ✅ - https://unrivaled-granita-99f32a.netlify.app/\nEnvironment: mainnet\nAuthor: ${{ github.actor }}\n❗️❗️❗️ TEST SDK ENVIRONMENT ❗️❗️❗️"
