import {
  AiFillHeart,
  AiFillStar,
  AiOutlineHeart,
  AiOutlineInfo,
  AiOutlineInfoCircle,
  AiOutlineLineChart,
  AiOutlineMenu,
  AiOutlineQrcode,
  AiOutlineSend,
  AiOutlineStar,
  AiOutlineSwap,
} from 'react-icons/ai'
import {
  BiDollarCircle,
  BiArrowBack,
  BiLinkExternal,
  BiSelectMultiple,
} from 'react-icons/bi'
import {
  BsCurrencyDollar,
  BsDiscord,
  BsEmojiSmile,
  BsMedium,
  BsQuestion,
  BsQuestionCircle,
  BsSearch,
  BsTelegram,
  BsThreeDots,
  BsTwitter,
} from 'react-icons/bs'
import { CgMenu, CgArrowsExchangeAltV, CgEye } from 'react-icons/cg'
import {
  FaChartArea,
  FaChartPie,
  FaFire,
  FaGasPump,
  FaSortDown,
  FaSortUp,
  FaWifi,
  FaArrowDown,
} from 'react-icons/fa'
import {
  FiCheck,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiEdit,
  FiPlus,
  FiX,
  FiXCircle,
} from 'react-icons/fi'
import { HiOutlineCog, HiOutlineChartPie } from 'react-icons/hi'
import {
  IoCheckmarkCircleOutline,
  IoCloseCircleOutline,
  IoWalletOutline,
  IoLanguage,
} from 'react-icons/io5'
import {
  MdAreaChart,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  MdLanguage,
  MdOutlineLock,
  MdOutlineLockOpen,
  MdSpaceBar,
  MdOutlineHdrAuto,
} from 'react-icons/md'
import { RiShareBoxLine } from 'react-icons/ri'
import {
  VscAdd,
  VscCloudUpload,
  VscCopy,
  VscHistory,
  VscKey,
  VscSignOut,
  VscSymbolMethod,
} from 'react-icons/vsc'

import { SvgIcons } from './svg/svgIconList'

const Icons = {
  add: VscAdd,
  arrowBack: BiArrowBack,
  arrowDown: FaArrowDown,
  arrowUp: MdKeyboardArrowUp,
  arrowUpLine: MdKeyboardArrowUp,
  arrowDownLine: MdKeyboardArrowDown,
  arrowLeftLine: MdKeyboardArrowLeft,
  arrowRightLine: MdKeyboardArrowRight,
  auto: MdOutlineHdrAuto,
  backup: VscCloudUpload,
  chart: AiOutlineLineChart,
  chartArea2: FaChartArea,
  chartArea: MdAreaChart,
  chartPie: FaChartPie,
  chartPieOutline: HiOutlineChartPie,
  checkmark: FiCheck,
  chevronDown: FiChevronDown,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  close: FiX,
  cog: HiOutlineCog,
  copy: VscCopy,
  currencyDollar: BsCurrencyDollar,
  dashboard: VscHistory,
  disconnect: VscSignOut,
  discord: BsDiscord,
  dollarOutlined: BiDollarCircle,
  edit: FiEdit,
  exchange: CgArrowsExchangeAltV,
  external: BiLinkExternal,
  eye: CgEye,
  fire: FaFire,
  gas: FaGasPump,
  info: AiOutlineInfo,
  infoCircle: AiOutlineInfoCircle,
  invalid: IoCloseCircleOutline,
  key: VscKey,
  language: MdLanguage,
  languageLetters: IoLanguage,
  list: AiOutlineMenu,
  lock: MdOutlineLock,
  medium: BsMedium,
  menu: CgMenu,
  node: VscSymbolMethod,
  qrcode: AiOutlineQrcode,
  question: BsQuestion,
  questionCircle: BsQuestionCircle,
  plus: FiPlus,
  search: BsSearch,
  send: AiOutlineSend,
  share: RiShareBoxLine,
  smile: BsEmojiSmile,
  sortDown: FaSortDown,
  sortUp: FaSortUp,
  switch: AiOutlineSwap,
  telegram: BsTelegram,
  threeDotsHorizontal: BsThreeDots,
  twitter: BsTwitter,
  unlock: MdOutlineLockOpen,
  valid: IoCheckmarkCircleOutline,
  wallet: IoWalletOutline,
  wifi: FaWifi,
  xCircle: FiXCircle,
  selectAll: BiSelectMultiple,
  spaceBar: MdSpaceBar,
  starFilled: AiFillStar,
  starEmpty: AiOutlineStar,
  heart: AiOutlineHeart,
  heartFilled: AiFillHeart,
  ...SvgIcons,
} as const

export default Icons
